language: node_js
node_js:
  - 8
branches:
  only:
    - master
script:
  - npm test
install:
  - npm install
after_success:
  - npm run coveralls

env:
  global:
    - secure: fC4lQvjCGT/zuuuAau33MpW24Sq5I4jXuYebizb7ravaq3nNt2J26dEbb7+mP6X1wst9+d93nba2JF5NwSRs34BZPyr3g3KFMcxuYwUtaXtLA62H3HqXq2EhtXQjd5q4PJfWkjCKJ23V9Gq02USbP9SAS0w4aFALgwQm+UHX+/xTU9yUcM3s3uiAZM5GDXum490jHEXKBB2twUuALkyuEe1UqesUY1CHh/klRSaHuZ0oBXH/41GZ+qf9btHKYnZxp1wrFuSNGW5sv+qKUtH+rBTrprJ80WQVBRmjOnKOI7R1RXbDomnK0RdrD79Erid9Nwy6Wdq45QQ5Ab6IEZ+YxueuTZP0JpFIgyUJc38Q7dRuMlvy0BKkmbBnMoMFvENYvYespLTjYuQtW0xC1YEgxwirqgRE0Xv2qfqyxci7+ZkNf8GR0EwzlsYqwHay9YYHqqomazVvzIYmJ7QsPfQ1+MRIE7ckNFgHWr2s4Mi/jyyYpIra0DxjW4NGCSrLgOxo68tJWzaT2idgM0miuVkER+TQDRr+P+tDeJdHCBvB9F/mUgzx9sbkJAyG6WTHc4ErYXab7JxvWVeqS3o2pBrPOy7JCjhZ8/VQjP1Er0jDienJdCsBlg+MfJ/SYFOXzK96DTcY9l+IyWO47q5xJccVhAoilaaYex/kUL5MCeLnSn8=
